#!/usr/bin/env python3
import glob
import os
import re
import collections
from bs4 import BeautifulSoup

def get_title(filename):
    with open(filename) as f:
        html = BeautifulSoup(f.read(), 'html.parser')
        text = ' '.join(map(str,html.h1.children))
        return text.replace('<p>', '').replace('</p>','')

iso = re.compile('([pd])(\d{4})r(\d+).html')
papers = collections.defaultdict(list)
others = []

for filename in glob.glob(f'*/*.html'):
    path, base = os.path.split(filename)
    if path in ('sd6', 'md'):
        continue

    m = iso.match(base)
    if m:
        pd, num, rev = m.groups()
        num = int(num)
        rev = int(rev)
        papers[num].append((rev, pd, path, filename))
    else:
        others.append((base, filename))

out = open('all_papers.md', 'w')
print('# Papers with Numbers', file=out)
titles = {847: "Deducing `this`"}
for num in sorted(papers):
    vals = sorted(papers[num])
    path = vals[-1][2]
    title = titles.get(num)
    if title is None:
        title = get_title(vals[-1][-1])
    all_revs = ' '.join(f'[{pd}{num:04d}r{rev}]({filename})' for (rev, pd, path, filename) in vals)
    print(f'- {num} {title}: {all_revs}', file=out)

print(file=out)
print('# Other Papers', file=out)
for (base, filename) in sorted(others):
    print(f'- {get_title(filename)}: [{base}]({filename})', file=out)
