p1188r0.html : spaceship-lib.md
	python ../md/better_md.py -i $< -o $@ --references

p1185r1.html : spaceship-no-eq.md
	python ../md/better_md.py -i $< -o $@ --references

p1186r1.html : spaceship-is-compare.md
	python ../md/better_md.py -i $< -o $@ --references
